In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.2'

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 15, 3)

array([ 1,  4,  7, 10, 13])

In [5]:
np.arange(1, 30, 0.7)

array([ 1. ,  1.7,  2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,  8. ,
        8.7,  9.4, 10.1, 10.8, 11.5, 12.2, 12.9, 13.6, 14.3, 15. , 15.7,
       16.4, 17.1, 17.8, 18.5, 19.2, 19.9, 20.6, 21.3, 22. , 22.7, 23.4,
       24.1, 24.8, 25.5, 26.2, 26.9, 27.6, 28.3, 29. , 29.7])

In [6]:
np.random.randn(3, 4)

array([[-0.1914884 , -1.50327644, -2.10053046,  2.49516653],
       [-0.26856564,  1.41528519, -0.52077622, -0.67891988],
       [-0.439483  , -0.23623642, -1.19667376, -0.73892363]])

In [7]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.arange(12).reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
np.arange(12).reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])